name: Release

on:
  workflow_dispatch:
    inputs:
      forceVersion:
        description: 'Force version'
        required: true
        default: ''

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Git tag
        id: 'next-version'
        run: |
          git tag ${FORCE_VERSION}
          git push --tags
          NEW_APPLICATION_VERSION=${FORCE_VERSION}
          echo "::set-output name=next_version::$NEW_APPLICATION_VERSION"
        env:
          FORCE_VERSION: ${{ github.event.inputs.forceVersion }}

      - name: Create release on GitHub
        run: |
          TODAY_DD_MM_YYYY=$(date +'%d.%m.%Y')

          create_release_body()
          {
            cat <<EOF
          {
              "tag_name":"$CURRENT_APPLICATION_VERSION",
              "target_commitish":"master",
              "name":"$CURRENT_APPLICATION_VERSION (${TODAY_DD_MM_YYYY})",
              "draft":false,
              "prerelease":false,
              "generate_release_notes":false
          }
          EOF
          }

          curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/pitagoras3/gh-project-test/releases \
            -d "$(create_release_body)"
        env:
          CURRENT_APPLICATION_VERSION: ${{ steps.next-version.outputs.next_version }}
      
      - name: Generate release notes on GitHub
        run: |
          generate_release_notes_body()
          {
            cat <<EOF
          {
              "tag_name":"$CURRENT_APPLICATION_VERSION",
              "target_commitish":"master",
              "previous_tag_name":"$PREVIOUS_APPLICATION_VERSION"
          }
          EOF
          }

          curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/pitagoras3/gh-project-test/releases/generate-notes \
            -d "$(generate_release_notes_body)"
        env:
          CURRENT_APPLICATION_VERSION: ${{ steps.next-version.outputs.next_version }}
          PREVIOUS_APPLICATION_VERSION: ${{ steps.previoustag.outputs.tag }}
