name: Release

on:
  workflow_dispatch:
    inputs:
      forceVersion:
        description: 'Force version'
        required: true
        default: ''

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Git tag
        id: 'next-version'
        run: |
          git tag ${FORCE_VERSION}
          git push --tags
          NEW_APPLICATION_VERSION=${FORCE_VERSION}
          echo "::set-output name=next_version::$NEW_APPLICATION_VERSION"

      - name: Generate release notes on GitHub
        run: |
          TODAY_DD_MM_YYYY=$(date +'%d.%m.%Y')

          generate_post_data()
          {
            cat <<EOF
          {
              "tag_name":"$APPLICATION_VERSION",
              "target_commitish":"master",
              "name":"$APPLICATION_VERSION (${TODAY_DD_MM_YYYY})",
              "draft":false,
              "prerelease":false,
              "generate_release_notes":true
          }
          EOF
          }

          curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/pitagoras3/gh-project-test/releases \
            -d "$(generate_post_data)"
        env:
          APPLICATION_VERSION: ${{ steps.next-version.outputs.next_version }}
