name: Release

on:
  workflow_dispatch:
    inputs:
      forceVersion:
        description: 'Force version'
        required: true
        default: ''

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Git tag
        run: |
          git tag ${FORCE_VERSION}
          git push --tags
        env:
          FORCE_VERSION: ${{ github.event.inputs.forceVersion }}
      - name: Generate release notes on GitHub
        run: |
          TODAY_DD_MM_YYYY=$(date +'%d.%m.%Y')
          curl -v -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          https://api.github.com/repos/pitagoras3/gh-project-test/releases \
          -d '{"tag_name":"'"${FORCE_VERSION}"'","target_commitish":"master","name":"'"${FORCE_VERSION}"' ('"${TODAY_DD_MM_YYYY}"')","draft":false,"prerelease":false,"generate_release_notes":true}'
