name: Release

on:
  workflow_dispatch:
    inputs:
      forceVersion:
        description: 'Force version'
        required: true
        default: ''

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: 'Previous version'
        if: github.ref == 'refs/heads/master'
        id: 'previous-version'
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Git tag
        if: github.ref == 'refs/heads/master'
        id: 'next-version'
        run: |
          git tag ${FORCE_VERSION}
          git push --tags
          NEW_APPLICATION_VERSION=${FORCE_VERSION}
          echo "::set-output name=next_version::$NEW_APPLICATION_VERSION"
        env:
          FORCE_VERSION: ${{ github.event.inputs.forceVersion }}

      - name: Generate release notes
        if: github.ref == 'refs/heads/master'
        id: 'release-notes'
        run: |
          generate_release_notes_body()
          {
            cat <<EOF
          {
              "tag_name":"$CURRENT_APPLICATION_VERSION",
              "target_commitish":"master",
              "previous_tag_name":"$PREVIOUS_APPLICATION_VERSION"
          }
          EOF
          }

          RELEASE_NOTES_MARKDOWN=$(curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/pitagoras3/gh-project-test/releases/generate-notes \
            -d "$(generate_release_notes_body)" \
            | jq -r '.body')
          
          echo "::set-output name=release_notes_markdown::$RELEASE_NOTES_MARKDOWN"
          echo $RELEASE_NOTES_MARKDOWN
        env:
          CURRENT_APPLICATION_VERSION: ${{ steps.next-version.outputs.next_version }}
          PREVIOUS_APPLICATION_VERSION: ${{ steps.previous-version.outputs.tag }}
      
      - name: Create release on GitHub
        if: github.ref == 'refs/heads/master'
        run: |
          echo $RELEASE_NOTES_MARKDOWN
          TODAY_DD_MM_YYYY=$(date +'%d.%m.%Y')

          create_release_body()
          {
            cat <<EOF
          {
              "tag_name":"$CURRENT_APPLICATION_VERSION",
              "target_commitish":"master",
              "name":"$CURRENT_APPLICATION_VERSION (${TODAY_DD_MM_YYYY})",
              "draft":false,
              "prerelease":false,
              "generate_release_notes":false,
              "body":"$RELEASE_NOTES_MARKDOWN"
          }
          EOF
          }

          curl -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/pitagoras3/gh-project-test/releases \
            -d "$(create_release_body)"
        env:
          CURRENT_APPLICATION_VERSION: ${{ steps.next-version.outputs.next_version }}
          RELEASE_NOTES_MARKDOWN: ${{ steps.release-notes.outputs.release_notes_markdown }}
